### ISSUE TITLE
project meeting #2

### ISSUE THREAD

**Issue by alexacmoldovan** [alexacmoldovan/BabaYaga#9]

**Comment by alexacmoldovan** [comment]
(https://docs.google.com/document/d/1D0HqQEvoR4seAVTIio5TKLNd8SNaj-AQfK79BChwU14/edit?usp=sharing)

**Comment by MKesbird** [comment]
It wouldn't let me edit it with the link you gave me, so I'll just post the finished link. I emailed it to our professor.

https://docs.google.com/document/d/1nJvRR7yKIp1dXu07r86qZiuCqm1Nxbf-TUxCKoKqapU/edit
